language: cpp
os:
  - linux
  - osx
branches:
  only:
    - master
compiler:
  - gcc
  - clang
before_install:
  - cp golded3/mygolded.__h golded3/mygolded.h
script:
  - CFLAGS="-Wno-keyword-macro -Wno-c++11-compat-deprecated-writable-strings -Wno-write-strings" CPPLAGS="${CFLAGS}" make
