version: '{build}'
branches:
  only:
    - master
image:
  - Visual Studio 2017
platform:
  - Win32
  - x64
configureation:
  - Release
install:
  - cmd: copy golded3\mygolded.__h golded3\mygolded.h
build:
  parallel: true
  project: golded.vs2017.sln
artifacts:
  - path: windows/bin/$(configuration)/$(platform)/*.exe
deploy:
- provider: BinTray
  username: askovpen
  api_key:
    secure: tMeaumPwuXUoehCCRudxUm5bjBOmz7ZWkmpE1zM6/mZBBgEgJxBJ3yajiBpKcZ6J
  subject: askovpen
  repo: test
  package: golded-plus
  publish: true
