version: '{build}'
branches:
  only:
    - master
image:
  - Visual Studio 2017
platform:
  - Win32
  - x64
configuration:
  - Release
install:
  - cmd: copy golded3\mygolded.__h golded3\mygolded.h
build:
  parallel: true
  project: golded.vs2017.sln
after_build:
  cmd: 7z a golded-plus-%PLATFORM%.zip windows/bin/%CONFIGURATION%/%PLATFORM%/*.exe
artifacts:
  - path: golded-plus-*.zip
