version: '{build}'
branches:
  only:
    - master
    - /^golded-.*/
environment:
   matrix:
    - generator: Visual Studio 10 2010
      image: Visual Studio 2015
    - generator: Visual Studio 10 2010 Win64
      image: Visual Studio 2015
    - generator: Visual Studio 15 2017
      image: Visual Studio 2017
    - generator: Visual Studio 15 2017 Win64
      image: Visual Studio 2017
install:
  - cmd: copy golded3\mygolded.__h golded3\mygolded.h
build_script:
  - cmd: mkdir build && cd build && cmake --version
  - cmd: cmake .. -G "%GENERATOR%" 
  - cmd: cmake --build . -- /P:Configuration=Release
  - cmd: cpack

artifacts:
  - path: build\*.7z
    name: dist

deploy:
  provider: GitHub
  artifact: dist
  auth_token: $(GITHUB_OAUTH_TOKEN)
  on:
    appveyor_repo_tag: true
    IMAGE: Visual Studio 2015
