version: '{build}'
branches:
  only:
    - master
image:
  - Visual Studio 2017
environment:
  matrix:
  - TARGET: cygwin
  - TARGET: vs2017
install:
  - cmd: copy golded3\mygolded.__h golded3\mygolded.h
build_script:
  - cmd: if "%TARGET%"=="vs2017" (
      msbuild "C:\projects\golded-plus\golded.vs2017.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:Platform=Win32 &&
      msbuild "C:\projects\golded-plus\golded.vs2017.sln" /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:Platform=x64 )
  - cmd: if "%TARGET%"=="cugwin" (
      xcopy /i /q /s C:\projects\golded-plus C:\cygwin\home\appveyor\golded-plus &&
      C:\cygwin\bin\bash -e -l -c "cd golded-plus && ./dist-gpw.sh" )
