version: '{build}'
branches:
  only:
    - master
image:
  - Visual Studio 2017
platform:
  - Win32
  - x64
configuration:
  - Release
install:
  - cmd: copy golded3\mygolded.__h golded3\mygolded.h
build:
  parallel: true
  project: golded.vs2017.sln
after_build:
  cmd: 7z a golded-%PLATFORM%.zip windows/bin/%CONFIGURATION%/%PLATFORM%/*.exe
artifacts:
  - path: golded-*.zip
deploy:
- provider: BinTray
  username: askovpen
  api_key:
    secure: tMeaumPwuXUoehCCRudxUm5bjBOmz7ZWkmpE1zM6/mZBBgEgJxBJ3yajiBpKcZ6J
  subject: askovpen
  repo: test
  package: golded-plus
  publish: true
  version: latest
  override: true
  on:
    branch: master
